apiVersion: nfd.kubernetes.test/v1alpha1
kind: LabelRule
metadata:
  name: my-rule
  namespace: node-feature-discovery
spec:
  rules:
  #
  # A dummy example profile that is supposed to match virtually any Intel-based system
  #
  - name: profile.node.kubernetes.io/my-custom-crd-label
    matchAll:
    # Check that at least one PCI device with Intel as a vendor is present
    - pci.device:
        "vendor": { op: In, value: ["8086"] }
