apiVersion: nfd.kubernetes.test/v1alpha1
kind: LabelRule
metadata:
  name: rule-4
spec:
  rules:
  #
  # Complex rule demonstrating current capabilities
  #
  - name: "intel.com/label-4"
    matchAny:
    - kernel.loadedmodule:
        "kvm_intel": { op: Exists }
        "intel_cstate": { op: Exists }
      kernel.config:
        "PREEMPT_VOLUNTARY": { op: IsTrue }
        "IMA_DEFAULT_HASH": { op: In, value: ["sha1"] }
      kernel.version:
        "major": { op: Gt, value: ["4"] }
        "minor": { op: In, value: ["3", "4", "5"] }
      system.name:
        "nodename": { op: InRegexp, value: ["desk.*"] }
      system.osrelease:
        "NAME": { op: In, value: ["CentOS Linux"] }
        "VERSION_ID": { op: Gt, value: ["6"] }
      cpu.cpuid:
        "VMX": { op: Exists }
        "SSE4": { op: Exists }
        "SSE42": { op: Exists }
      cpu.cstate:
        "enabled": { op: IsTrue }
      cpu.pstate:
        "status": { op: In, value: ["active"] }
        "scaling_governor": { op: In, value: ["powersave"] }
      cpu.rdt:
        "RDTL3CA": { op: Exists }
        "RDTMBM": { op: Exists }
      cpu.topology:
        "hardware_multithreading": { op: IsTrue }
      usb.device:
        class: { op: In, value: ["09"] }
        vendor: { op: In, value: ["8087"] }

    matchAll:
    - pci.device:
        class: { op: In, value: ["0200"] }
        vendor: { op: In, value: ["8086"] }
        device: { op: In, value: ["15a1", "1017"] }
    - pci.device:
        class: { op: In, value: ["0300"] }
        vendor: { op: In, value: ["10de"] }
        device: { op: In, value: ["1380"] }
