apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  namespace: demo
spec:
  containers:
  - image: k8s.gcr.io/pause
    name: pause
  nodeSelector:
    feature.node.kubernetes.io/cpu-pstate.turbo: 'true'

